[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
arpay = "8TySTE3dpxVBU9dBkVxG9Lesk4N57om8Bo94aeZJS2zF"

[programs.devnet]
arpay = "8TySTE3dpxVBU9dBkVxG9Lesk4N57om8Bo94aeZJS2zF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"